project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "metaforr"
  author:
    - Bhargav Kantheti (bk2899)
    - Ryuichiro Sonoda (rs4493)
  repo-url: https://github.com/metaforr/metafor/
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: lux
    code-fold: true

